### ISSUE TITLE
Error after extension installation [v1.12.1] on vscode

### ISSUE THREAD

**Issue by siwalikm** [kisstkondoros/csstriggers#10]
Getting erro `[Error - 1:37:52 AM] (node:50486) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
` ever since I installed it. ANy hints on where to look?

**Comment by kisstkondoros** [comment]
It seems that one of the installed extensions on your system disables TLS verification.
Please try to locate the issue by disabling your extensions one by one as this might lead to a security issue.
You can check https://github.com/microsoft/vscode/issues/69559 for further details on this.

Just to be clear: this extension is doing nothing like this.
