### ISSUE TITLE
Icon borders too dark on other themes

### ISSUE THREAD

**Issue by mariusmateoc** [kisstkondoros/csstriggers#12]
I think if you would make borders from icons transparent or remove them it will look nicer on lighter themes too.

Also, it would be nice other options for icons, custom icons or custom colors.

**Comment by kisstkondoros** [comment]
Good idea, I'll investigate this soon

**Comment by kisstkondoros** [comment]
This should be now in the new version (v0.13.1)
The border was removed, icons can be recolored with some new properties (and also completely replaced, as the SVG templates are configurable too)
