### ISSUE TITLE
[BUG] Multiple icons and position with `showDecorationInline`

### ISSUE THREAD

**Issue by mariusmateoc** [kisstkondoros/csstriggers#13]
The position for the icon is not vertically centered when `"csstriggers.showDecorationInline": true`. I think it should be centered by keeping in mind the option `"editor.lineHeight"`.

![image](https://user-images.githubusercontent.com/2094443/80398882-a3b30580-88b8-11ea-8fa7-2575e23d7a88.png)

If I click on the left icon that marks that this row was changed to see the changes when that window opens it adds a new icon next to old one also when using `"csstriggers.showDecorationInline: true"  

![image](https://user-images.githubusercontent.com/2094443/80399161-099f8d00-88b9-11ea-860a-28ecdfe6ae52.png)

**Comment by kisstkondoros** [comment]
Thanks for the issue report, I'll look into this soon.

I suppose the inline decoration falls into the same location, but rendered in the wrong position, because of the diff viewer...

**Comment by kisstkondoros** [comment]
This should be fixed now in the new version (v0.13.1)

**Comment by mariusmateoc** [comment]
Thanks, now it works and keeps an account for `"editor.lineheight"` option but don't avoid the duplication of inline decorator after using the diff viewer. I'm using the new version (v0.13.1)

![show-inline-error](https://user-images.githubusercontent.com/2094443/83503970-32243380-a4c4-11ea-8fc9-63bd13396de6.gif)
