### ISSUE TITLE
[Feature request] Add support to logical properties and values

### ISSUE THREAD

**Issue by ahmadalfy** [kisstkondoros/csstriggers#15]
CSS logical properties and values are currently an [Editor's Draft ](https://drafts.csswg.org/css-logical/). We use it heavily and transform it into the corresponding values using PostCSS plugins. Adding support would help those who use it as well.

If you don't mind supporting these properties and values I will be glad to submit a PR.

Thank you for your awesome work on this extension

**Comment by kisstkondoros** [comment]
This is a good idea!
Feel free to submit a solution for this!

**Comment by kisstkondoros** [comment]
Perhaps try if adding a mapping makes it work at https://github.com/kisstkondoros/csstriggers/blob/efcf977d686daafbd9140097798089d480e8a77b/src/server/liveData.ts#L30

**Comment by ahmadalfy** [comment]
That's a great idea I think it will work easily. Will make the necessary changes and submit the PR. That would actually be easier than I thought 😂
