### ISSUE TITLE
Please add 'stylable' language to activation events

### ISSUE THREAD

**Issue by tempit** [kisstkondoros/csstriggers#2]
Hi, we're writing a CSS preprocessor which comes with an LSP-vased VSCode extension. 
We have people working with csstrigers, who have lost the functionality since our extension contributes a new language.
Can you please add "onLanguage:stylable" to the activation events, so we can keep using this extension?

**Comment by kisstkondoros** [comment]
Stylable support has been added, it was not an easy ride since I had to upgrade the project setup...

So, take it while it's hot: v0.4.0 is in the market already! :fireworks:

**Comment by idoros** [comment]
works great, thanx!
