### ISSUE TITLE
Vue file support.

### ISSUE THREAD

**Issue by nereuseng** [kisstkondoros/csstriggers#4]
Thank you so much for creating this extension!
I am really enjoy from your work.
Is that possible to make .vue file to support this extension?
Recently I have a project with vuejs and find out this useful tools not working on .vue files
It will be great if .vue file supported!
Thank you again for this handy tools!

**Comment by kisstkondoros** [comment]
Vue support landed in v0.6.0, it should be available in the market already. :fireworks:
