### ISSUE TITLE
css-in-js support (styled-components, emotion et al)

### ISSUE THREAD

**Issue by Jessidhia** [kisstkondoros/csstriggers#8]
Some popular React libraries let you write CSS inline by way of a special template tag. For example, https://www.styled-components.com/:

![image](https://user-images.githubusercontent.com/73085/49980799-499df280-ff98-11e8-87d6-2b6ab6a4405f.png)

Would be nice if this could work, in combination with https://github.com/styled-components/vscode-styled-components, to support annotating them.

--

Newer versions of `styled-components` also support specifying the style as a CSS-like object (`{ display: 'inline-block', borderRadius: 3, padding: '0.5rem 0', ... }`), but supporting that is probably a lot more difficult than supporting the base case of plain-css-like syntax.

**Comment by kisstkondoros** [comment]
Thanks for the issue report, csstriggers@0.9.0 was just published to add this feature.

Since extensions could not access any scope information I couldn't limit it to template literals and / or object literals. (see microsoft/vscode#580)
