### ISSUE TITLE
Causes conflicts with other extensions that use margins

### ISSUE THREAD

**Issue by COD3BREAK3R** [kisstkondoros/csstriggers#9]
Thanks for creating this extension. It works well but causes conflicts with other extensions that make use of margins such as Margin Colors or  Brackets Pair Colorizer, is there any way to expand the margin limit or other alternative to solve this problem? Maybe you could put a configuration that allows you to put the cost indicator in another place as for example within the editor or next to the properties, maybe create rights margins, and that all this is configurable to suit the user.

**Comment by kisstkondoros** [comment]
It is a a general vscode issue, see https://github.com/Microsoft/vscode/issues/5923

I'll consider the configurability of the location for the indicator.

**Comment by kisstkondoros** [comment]
A new option to show decorations inline was added (`csstriggers.showDecorationInline`) in csstriggers@0.11.0.
